#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    password: "$6$.mXU.Raz4YERUY3P$ohe.s8CHkeQwDuetCRi4GGiXrd07irtJ51c7n1ujP15TR63m85nOkH83UCvh.YO90COxyJ3VLbLAcxD.sDqq90"
    username: ubuntu
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: true
        addresses: [192.168.1.254/24]
        gateway4: 192.168.1.1
        nameservers:
          addresses: [1.1.1.1,1.0.0.1]
        dhcp6: true
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys: ["$SSH_PUBKEY"]
  late-commands:
    - "lsb_release -a"
    - "ip -4 -br -a"
    - "touch /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "echo '#!/bin/sh' >> /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "echo 'set -e' >> /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "echo 'HOSTINFO=$(/usr/bin/lsb_release -a 2>&1 | grep Description | /usr/bin/cut -d \":\" -f2 | /usr/bin/tr -d [:blank:])' >> /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "echo 'IPADDRS=$(/usr/sbin/ip -4 -br a)' >> /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "echo '/usr/bin/echo -ne \"Host OS: $HOSTINFO\\n$IPADDRS\\n\" > /etc/issue' >> /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"
    - "chmod +x /etc/networkd-dispatcher/routable.d/add-ip-to-login-screen"