#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    password: "$6$.mXU.Raz4YERUY3P$ohe.s8CHkeQwDuetCRi4GGiXrd07irtJ51c7n1ujP15TR63m85nOkH83UCvh.YO90COxyJ3VLbLAcxD.sDqq90"
    username: ubuntu
  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: no
        addresses: [192.168.1.254/24]
        gateway4: 192.168.1.1
        nameservers:
          addresses: [1.1.1.1,1.0.0.1]
        dhcp6: true
  ssh:
    install-server: true
  early-commands:
    - "ping -c1 198.162.1.1"